# Generated by Django 4.1.5 on 2024-03-16 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyRoom', '0005_alter_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='likes',
        ),
        migrations.AddField(
            model_name='message',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_message', to=settings.AUTH_USER_MODEL),
        ),
    ]
