# Generated by Django 4.0.4 on 2024-07-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyRoom', '0010_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='icons/avatar.svg', null=True, upload_to='images'),
        ),
    ]
